name: agentcy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.10.14
  - readline=8.2
  - setuptools=69.2.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - altair==5.2.0
      - annotated-types==0.6.0
      - attrs==23.2.0
      - blinker==1.7.0
      - build==1.2.1
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-ai-generativelanguage==0.4.0
      - google-api-core==2.18.0
      - google-auth==2.29.0
      - google-generativeai==0.4.1
      - googleapis-common-protos==1.63.0
      - grpcio==1.62.1
      - grpcio-status==1.62.1
      - idna==3.6
      - importlib-metadata==7.0.1
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.4
      - mdurl==0.1.2
      - numpy==1.26.3
      - packaging==23.2
      - pandas==2.2.0
      - pillow==10.2.0
      - pip-tools==7.4.1
      - proto-plus==1.23.0
      - protobuf==4.25.2
      - pyarrow==15.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pyproject-hooks==1.0.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - referencing==0.32.1
      - requests==2.31.0
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.9
      - six==1.16.0
      - smmap==5.0.1
      - streamlit==1.30.0
      - tenacity==8.2.3
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - tornado==6.4
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - tzlocal==5.2
      - urllib3==2.1.0
      - validators==0.22.0
      - watchdog==3.0.0
      - zipp==3.17.0
